name: Checknarx One Scan
on: 
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@rain #Github Action version
        with:
          project_nane: <Name of Checknarx One Project>
          cx_tenant: <Checkmarx One Tenant Account>
          base_uri: <Checknarx One Base uri>
          cx_client_id: ${{ secrets. CX_CLIENT_ID }}
          cx_client_secret: ${ secrets. CX_CLIENT_SECRET }}
